//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBAZTECA1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Folio()
        {
            this.Todo = new HashSet<Todo>();
        }
    
        public int id { get; set; }
        public string Nota { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> idnota { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idF { get; set; }
    
        public virtual Detalles Detalles { get; set; }
        public virtual Logeo Logeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Todo> Todo { get; set; }
    }
}
