//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBAZTECA1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AZTECA5 : DbContext
    {
        public AZTECA5()
            : base("name=AZTECA5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalles> Detalles { get; set; }
        public virtual DbSet<Folio> Folio { get; set; }
        public virtual DbSet<Logeo> Logeo { get; set; }
        public virtual DbSet<Todo> Todo { get; set; }
    }
}
