//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBAZTECA1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int id { get; set; }
        public Nullable<int> IdLogeo { get; set; }
        public Nullable<int> IdFolio { get; set; }
        public Nullable<int> IdDetalles { get; set; }
    
        public virtual Detalles Detalles { get; set; }
        public virtual Folio Folio { get; set; }
        public virtual Logeo Logeo { get; set; }
    }
}
